version: "3.8"

services:
  server:
    build:
      context: ..
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/your_database_name
      SPRING_DATASOURCE_DRIVER: com.mysql.cj.jdbc.Driver
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - network

networks:
  network: